Change requirements txt

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -30,33 +30,6 @@ APP_LIBS="$(cat "${ENV_DIR}/APP_LIBS")"
 TMPAPP="${STAGE}/TEMP_APP"
 TMPLIBS="${STAGE}/TEMP_LIBS"
 
-# echo "${APP_BASE}"
-# echo "${APP_LIBS}"
-# echo "${TMPAPP}"
-# echo "${TMPLIBS}"
-
-# (
-#   mkdir "${TMPLIBS}" &&
-#   mkdir "${TMPAPP}" &&
-#   mv "${BUILD_DIR}/${APP_BASE}" "${TMPAPP}/$(basename "$APP_BASE")" &&
-#   mv "${BUILD_DIR}/${APP_LIBS}" "${TMPLIBS}/${APP_LIBS}" &&
-#   rm -rf "${BUILD_DIR}"/* &&
-#   mv "${TMPAPP}/$(basename "$APP_BASE")"/* "${BUILD_DIR}"
-#   mv "${TMPLIBS}"/* "${BUILD_DIR}"
-# )
-
-# if [ $? -ne 0 ]; then
-#     echo "FAILED to copy directories into place" | indent
-#     exit 1
-# fi
-
-# # ------------------ CHANGE toml file ----------------
-# for lib in "$ENV_DIR"/RAIDER_POETRY_LIB_* ; do
-#     echo "${BUILD_DIR}/${APP_LIBS}/$(cat "$lib")"
-#     sed -i -e "s,$(cat "$lib")\s=\s{.*},$(cat "$lib") = {path = \""${APP_LIBS}/$(cat "$lib")"\"},g" "${BUILD_DIR}/pyproject.toml"
-# done
-
-# cat "${BUILD_DIR}/pyproject.toml"
 
 # ----------------- POETRY ------------------------------------
 
@@ -116,37 +89,68 @@ poetry lock --no-update
 poetry export -f "$REQUIREMENTS_FILE" "${EXPORT_PARAMETERS[@]}" > "$REQUIREMENTS_FILE.orig"
 sed -e 's/^-e //' < "$REQUIREMENTS_FILE.orig" > "$REQUIREMENTS_FILE" && rm "$REQUIREMENTS_FILE.orig"
 
-# RUNTIME_FILE="runtime.txt"
+RUNTIME_FILE="runtime.txt"
 
-# log "Export Python version from Poetry to Heroku $RUNTIME_FILE file"
+log "Export Python version from Poetry to Heroku $RUNTIME_FILE file"
 
-# if [ "${DISABLE_POETRY_CREATE_RUNTIME_FILE:-0}" != "0" ] ; then
-#     log "Skip generation of $RUNTIME_FILE file from poetry.lock"
-#     exit 0
-# fi
+if [ "${DISABLE_POETRY_CREATE_RUNTIME_FILE:-0}" != "0" ] ; then
+    log "Skip generation of $RUNTIME_FILE file from poetry.lock"
+    exit 0
+fi
 
-# if [ -f "$RUNTIME_FILE" ] ; then
-#     log "$RUNTIME_FILE found, delete this file from your repository!" >&2
-#     exit 1
-# fi
+if [ -f "$RUNTIME_FILE" ] ; then
+    log "$RUNTIME_FILE found, delete this file from your repository!" >&2
+    exit 1
+fi
 
-# if [ -z "${PYTHON_RUNTIME_VERSION:-}" ] ; then
-#     log "Read Python version from poetry.lock"
-#     PYTHON_RUNTIME_VERSION="$(sed -n -e '/^\[metadata\]/,/^\[/p' poetry.lock | sed -n -e 's/^python-versions\s*=\s*//p' | tr -d \"\')"
-# else
-#     log "Force Python version to $PYTHON_RUNTIME_VERSION, because PYTHON_RUNTIME_VERSION is set!"
-# fi
+if [ -z "${PYTHON_RUNTIME_VERSION:-}" ] ; then
+    log "Read Python version from poetry.lock"
+    PYTHON_RUNTIME_VERSION="$(sed -n -e '/^\[metadata\]/,/^\[/p' poetry.lock | sed -n -e 's/^python-versions\s*=\s*//p' | tr -d \"\')"
+else
+    log "Force Python version to $PYTHON_RUNTIME_VERSION, because PYTHON_RUNTIME_VERSION is set!"
+fi
 
-# # Version is only valid if exact interpreter version is specified
-# #
-# # ^3.8 -> not valid
-# # 3.8 -> not valid
-# # 3.8.1 -> valid
+# Version is only valid if exact interpreter version is specified
+#
+# ^3.8 -> not valid
+# 3.8 -> not valid
+# 3.8.1 -> valid
 
-# if [[ "$PYTHON_RUNTIME_VERSION" =~ ^[2-9](\.[0-9]+){2}$ ]] ; then
-#     log "Write $PYTHON_RUNTIME_VERSION into $RUNTIME_FILE"
-#     echo "python-$PYTHON_RUNTIME_VERSION" > "$RUNTIME_FILE"
-# else
-#     log "$PYTHON_RUNTIME_VERSION is not valid, please specify an exact Python version (e.g. 3.8.1) in your pyproject.toml (and thus poetry.lock)" >&2
-#     exit 1
-# fi
+if [[ "$PYTHON_RUNTIME_VERSION" =~ ^[2-9](\.[0-9]+){2}$ ]] ; then
+    log "Write $PYTHON_RUNTIME_VERSION into $RUNTIME_FILE"
+    echo "python-$PYTHON_RUNTIME_VERSION" > "$RUNTIME_FILE"
+else
+    log "$PYTHON_RUNTIME_VERSION is not valid, please specify an exact Python version (e.g. 3.8.1) in your pyproject.toml (and thus poetry.lock)" >&2
+    exit 1
+fi
+
+
+# ----------------------------------------------------------------------------------------------
+
+echo "${APP_BASE}"
+echo "${APP_LIBS}"
+echo "${TMPAPP}"
+echo "${TMPLIBS}"
+
+(
+  mkdir "${TMPLIBS}" &&
+  mkdir "${TMPAPP}" &&
+  mv "${BUILD_DIR}/${APP_BASE}" "${TMPAPP}/$(basename "$APP_BASE")" &&
+  mv "${BUILD_DIR}/${APP_LIBS}" "${TMPLIBS}/${APP_LIBS}" &&
+  rm -rf "${BUILD_DIR}"/* &&
+  mv "${TMPAPP}/$(basename "$APP_BASE")"/* "${BUILD_DIR}"
+  mv "${TMPLIBS}"/* "${BUILD_DIR}"
+)
+
+if [ $? -ne 0 ]; then
+    echo "FAILED to copy directories into place" | indent
+    exit 1
+fi
+
+# ------------------ CHANGE requirements.txt file ----------------
+for lib in "$ENV_DIR"/RAIDER_POETRY_LIB_* ; do
+    echo "${BUILD_DIR}/${APP_LIBS}/$(cat "$lib")"
+    sed -i -e "s,$(cat "$lib").*;,$(cat "$lib") @ file://"${APP_LIBS}/$(cat "$lib")"\"},g" "$REQUIREMENTS_FILE"
+done
+
+cat "$REQUIREMENTS_FILE"
