change pwd

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -30,35 +30,36 @@ APP_LIBS="$(cat "${ENV_DIR}/APP_LIBS")"
 TMPAPP="${STAGE}/TEMP_APP"
 TMPLIBS="${STAGE}/TEMP_LIBS"
 
-echo "${APP_BASE}"
-echo "${APP_LIBS}"
-echo "${TMPAPP}"
-echo "${TMPLIBS}"
+# echo "${APP_BASE}"
+# echo "${APP_LIBS}"
+# echo "${TMPAPP}"
+# echo "${TMPLIBS}"
 
-(
-  mkdir "${TMPLIBS}" &&
-  mkdir "${TMPAPP}" &&
-  mv "${BUILD_DIR}/${APP_BASE}" "${TMPAPP}/$(basename "$APP_BASE")" &&
-  mv "${BUILD_DIR}/${APP_LIBS}" "${TMPLIBS}/${APP_LIBS}" &&
-  rm -rf "${BUILD_DIR}"/* &&
-  mv "${TMPAPP}/$(basename "$APP_BASE")"/* "${BUILD_DIR}"
-  mv "${TMPLIBS}"/* "${BUILD_DIR}"
-)
+# (
+#   mkdir "${TMPLIBS}" &&
+#   mkdir "${TMPAPP}" &&
+#   mv "${BUILD_DIR}/${APP_BASE}" "${TMPAPP}/$(basename "$APP_BASE")" &&
+#   mv "${BUILD_DIR}/${APP_LIBS}" "${TMPLIBS}/${APP_LIBS}" &&
+#   rm -rf "${BUILD_DIR}"/* &&
+#   mv "${TMPAPP}/$(basename "$APP_BASE")"/* "${BUILD_DIR}"
+#   mv "${TMPLIBS}"/* "${BUILD_DIR}"
+# )
 
-if [ $? -ne 0 ]; then
-    echo "FAILED to copy directories into place" | indent
-    exit 1
-fi
+# if [ $? -ne 0 ]; then
+#     echo "FAILED to copy directories into place" | indent
+#     exit 1
+# fi
 
-# ------------------ CHANGE toml file ----------------
-for lib in "$ENV_DIR"/RAIDER_POETRY_LIB_* ; do
-    echo "${BUILD_DIR}/${APP_LIBS}/$(cat "$lib")"
-    sed -i -e "s,$(cat "$lib")\s=\s{.*},$(cat "$lib") = {path = \""${APP_LIBS}/$(cat "$lib")"\"},g" "${BUILD_DIR}/pyproject.toml"
-done
+# # ------------------ CHANGE toml file ----------------
+# for lib in "$ENV_DIR"/RAIDER_POETRY_LIB_* ; do
+#     echo "${BUILD_DIR}/${APP_LIBS}/$(cat "$lib")"
+#     sed -i -e "s,$(cat "$lib")\s=\s{.*},$(cat "$lib") = {path = \""${APP_LIBS}/$(cat "$lib")"\"},g" "${BUILD_DIR}/pyproject.toml"
+# done
 
-cat "${BUILD_DIR}/pyproject.toml"
+# cat "${BUILD_DIR}/pyproject.toml"
 
 # ----------------- POETRY ------------------------------------
+pushd "${APP_BASE}"
 
 BUILDPACK_VARIABLES="DISABLE_POETRY_CREATE_RUNTIME_FILE PYTHON_RUNTIME_VERSION"
 
@@ -116,6 +117,7 @@ poetry lock --no-update
 poetry export -f "$REQUIREMENTS_FILE" "${EXPORT_PARAMETERS[@]}" > "$REQUIREMENTS_FILE.orig"
 sed -e 's/^-e //' < "$REQUIREMENTS_FILE.orig" > "$REQUIREMENTS_FILE" && rm "$REQUIREMENTS_FILE.orig"
 
+popd
 # RUNTIME_FILE="runtime.txt"
 
 # log "Export Python version from Poetry to Heroku $RUNTIME_FILE file"
